- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 2.5h
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10h
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  radioBold: true # Sunrise-Edit
  displayWeight: 70 # Sunrise-Edit
  canBeAntag: true # RaMbUt878-edit
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ TrackingImplant, DeathRattleImplantBlueShield ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox # Sunrise-Edit

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
#    head: ClothingHeadHatHardhatWhite # Sunrise-Edit
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
  storage:
    back:
    - Flash
    - Telebaton # Sunrise-Edit

- type: chameleonOutfit
  id: ChiefEngineerChameleonOutfit
  job: ChiefEngineer
  hasMindShield: false #Sunrise-Edit
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckCloakCe
    outerClothing: ClothingOuterWinterCE
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMagAdv
