## Mercenary
advertisement-piratehumanoid-1 = Contact!
advertisement-piratehumanoid-2 = In position! Over.
advertisement-piratehumanoid-3 = Sights are cold!
advertisement-piratehumanoid-4 = Radio check. Over.
advertisement-piratehumanoid-5 = Check in. What's your status? Over.
advertisement-piratehumanoid-6 = Spread out!
advertisement-piratehumanoid-7 = Keep your eyes open!
advertisement-piratehumanoid-8 = Lost contact with the lookout. Over.
advertisement-piratehumanoid-9 = Finishing my patrol and heading back. Over.
advertisement-piratehumanoid-10 = Command, what's the sitrep? Over.
advertisement-piratehumanoid-11 = Target on the move!
advertisement-piratehumanoid-12 = Command, we've lost contact with the search team!
advertisement-piratehumanoid-13 = Fan out!
advertisement-piratehumanoid-14 = Any word on those reinforcements? Over.
advertisement-piratehumanoid-15 = I could use some reinforcements, command!
advertisement-piratehumanoid-16 = Orders received and understood! Over.
advertisement-piratehumanoid-17 = Watch your step.
advertisement-piratehumanoid-18 = Confirmed. Over.
advertisement-piratehumanoid-19 = In here. Over.
advertisement-piratehumanoid-20 = Neutralize the target!
## Pirate
advertisement-piratehumanoid-21 = Keep your blades sharp!
advertisement-piratehumanoid-22	= Quiet seas... too quiet.
advertisement-piratehumanoid-23	= Let ‘em come, we’re ready!
advertisement-piratehumanoid-24	= Smell that? Trouble’s close.
advertisement-piratehumanoid-25	= Gold or blood — both shine!
advertisement-piratehumanoid-26	= Don’t lower your guard, lads.
advertisement-piratehumanoid-27	= I miss the sound of a fight.
advertisement-piratehumanoid-28	= Keep eyes open, mates!
advertisement-piratehumanoid-29	= Hope the next ship’s worth it.
advertisement-piratehumanoid-30	= Calm before the storm, aye.
advertisement-piratehumanoid-31	= Who’s got the rum?
advertisement-piratehumanoid-32	= Can smell the credits already.
advertisement-piratehumanoid-33	= Sooner they show, sooner we loot!
advertisement-piratehumanoid-34	= The void’s watching…
## USSP
advertisement-piratehumanoid-35	= Stay alert, comrades.
advertisement-piratehumanoid-36	= Area secure... for now.
advertisement-piratehumanoid-37	= Keep weapons checked.
advertisement-piratehumanoid-38	= Feels like ambush weather.
advertisement-piratehumanoid-39	= Hold formation. Eyes up.
advertisement-piratehumanoid-40	= Breathe steady. Don’t relax.
advertisement-piratehumanoid-41	= Enemy won’t wait.
advertisement-piratehumanoid-42	= Silence is wrong.
advertisement-piratehumanoid-43	= Discipline keeps you alive.
advertisement-piratehumanoid-44	= No sign of movement. Yet.
advertisement-piratehumanoid-45	= Comms stable. Waiting.
advertisement-piratehumanoid-46	= Could use a smoke...
advertisement-piratehumanoid-47	= Keep sensors scanning.
advertisement-piratehumanoid-48	= Feels like before an operation.
advertisement-piratehumanoid-48	= Be ready to move, anytime.
