- type: antag
  id: PirateCaptain
  name: roles-antag-pirate-captain-name
  antagonist: true
  setPreference: true
  playTimeTracker: AntagPirateCaptain
  objective: roles-antag-pirate-captain-objective

- type: antag
  id: PirateCrew
  name: roles-antag-pirate-crew-name
  antagonist: true
  setPreference: true
  playTimeTracker: AntagPirateCrew
  objective: roles-antag-pirate-crew-objective

- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool

- type: startingGear
  id: PirateCaptainGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirate
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate

- type: startingGear
  id: PirateFirstmateGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateTricord
    outerClothing: ClothingOuterCoatGentle
